

export default {
  DYBLOGISTICS_RUNNING: "DYBLogistics is running on PORT",
  SUCCESS: "success",
  FAIL: "fail",
  v1: "/",
  RATE_NAME_ERROR: "Rate name (Express or Domestic) is required",
  RATE_NAME_UPDATE_ERROR: "Failed to update shipping rate",
  RATE_NAME_SUCCESS: 'Shipping rates fetched successfully',
  RATE_NAME_FAILURE: 'Failed to fetch shipping rates',
  RATE_NAME_CREATION_FAILURE: 'Failed to create shipping rates',
  EMPTY_EMAIL: 'Please enter your Email and password',
  EMAIL_CONFLICT: "A user with your email already exists",
  WELCOME: "Thanks for dropping by, you are at DYBLogistics",
  INVALID_CREDENTIALS: "Incorrect login details",
  INVALID_PERMISSION: "Permission denied. Invalid credentials provided",
  DB_SUCCESS: "Connected to Database Succssfully",
  DB_ERROR_STATUS: 'DB_PROCESS_FAILED',
  DB_ERROR: 'A database error occurred',
  FORBIDDEN: 'Access forbidden. You do not have the required access.',
  CREATE_USER_ERROR: 'Error creating user',
  LOGIN_USER_SUCCESSFULLY: "User Login successful",
  CREATE_USER_SUCCESS: 'Created user successfully',
  USER_ALREADY_EXIST: 'USER exists already',
  USERNAME_ALREADY_EXIST: 'USERNAME exists already',
  USER_EXIST_VERIFICATION_FAIL: 'USER_EMAIL_EXIST_VERIFICATION_FAIL',
  USER_EMAIL_EXIST_VERIFICATION_FAIL: 'USER_EMAIL_EXIST_VERIFICATION_FAIL',
  USER_EMAIL_EXIST_VERIFICATION_FAIL_MSG: 'Login failed. It is not you, it is us.',
  INTERNAL_SERVER_ERROR: 'Oops, something broke on the server!!!',
  INVALID_EMAIL: 'This email does not exist, please enter a registered email',
  USER_NOT_FOUND: 'User not found',
  SHIPPING_CREATION_SUCCESS: "Shipping created succesfully",
  SHIPPING_CREATION_FAILURE: "Failure in creating shipping",
  DASHBOARD_SUCCESS: "Dashboard loaded successfully",
  DASHBOARD_FAILURE: "Failure to load dashboard",
  ERROR_FETCHING_USER: 'Error fetching user',
  ERROR_VERIFYING_USER: 'ERROR VERIFYING USER',
  ERROR_VERIFYING_USER_MSG: 'Error trying to verify user. It is not you, it is us.',
  NOT_FOUND_API: 'Oops, You have reached a dead end',
};
